### ISSUE TITLE
(feature request) add tagging system

### ISSUE THREAD

**Issue by 5c0tt-b0t** [Super-Lovers/slbmsjs-cli#1]
Thank you! works nicely on both my laptop and my android phone! (termux). 
Search by keywords is very effective but links from youtube/spotify/etc... do not contain keywords, so allow some sort of tagging system and it'll be BEAUTIFUL! :)

**Comment by Super-Lovers** [comment]
Oh, I legit didn't expect anyone requesting anything on my projects, sure man, i'll see what I can do in my free time!

**Comment by 5c0tt-b0t** [comment]
😆 I expect this project will get busier in time, I see it getting popular as it is very good!! well done!
Thanks for considering the feature (I think it'll be great!)
I ask as I have quite alot of playlist links from youtube/spotify (from the gif it looks like you do too!), currently they are just links but with either: "tags" and/or "titles" added,  we could tag multiple playlists "HipHop" or "LoFi" etc. Obviously "titles" could further allow more, e.g. could then name a link to an idividual song "Logic - 44 More", whereas with tags-only it would probably be 
just "Logic". With both "tags" & "titles" that link could be titled "Logic - 44 More" and tagged "Logic" also. PERFECTION. 
Thank you again! its appreciated!!! 👍

**Comment by Super-Lovers** [comment]
@5c0tt-b0t I added tagging in the new version that was just uploaded, you can try out if everything works fine since you're the only one that can test. You can assign tags to one or more bookmarks by going to "> Tags" and then "> Assign Tags". This will let you search for links using keywords and then you can select any links you want to then tag. I will update the README or make a new one to include updated instructions soon.

**Comment by 5c0tt-b0t** [comment]
@Super-Lovers I apologise! I have JUST got back from holiday and turned on the PC!
**THANK YOU SO MUCH! its really appreciated.**
Just updated and gonna go test, test, test! will let you know ASAP :)

**Comment by Super-Lovers** [comment]
> @Super-Lovers I apologise! I have JUST got back from holiday and turned on the PC!
> **THANK YOU SO MUCH! its really appreciated.**
> Just updated and gonna go test, test, test! will let you know ASAP :)

No worries man, I just hope it's useful to you or that I didn't break anything xD

**Comment by Super-Lovers** [comment]
I will open a new issue for removing existing tags because I couldn't do that last time, so you can expect that soon
